## Automation

- alias: Turn on pole light when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.front_pole_light_level
      brightness_pct: 25

- alias: Turn off pole light when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:00:00"
  action:
    service: light.turn_off
    entity_id: light.front_pole_light_level

- alias: Turn on back porch light when motion, at night
  initial_state: True
  hide_entity: False
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "01:00:00"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_back_porch_sensor
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.back_porch_light_switch

- alias: Turn off back porch light 10 minutes after movement
  initial_state: True
  hide_entity: False
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "01:00:00"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_back_porch_sensor
    to: 'off'
    for:
      minutes: 10
  action:
    service: switch.turn_off
    entity_id: switch.back_porch_light_switch

- alias: Turn on the christmas lights when sun sets
  initial_state: 'off'
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"
  action:
    service: switch.turn_on
    entity_id:
      - switch.outdoor_relay_1_switch
      - switch.indoor_relay_2_switch

- alias: Turn off the christmas lights at 23:30
  initial_state: 'off'
  hide_entity: False
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: switch.turn_off
    entity_id:
      - switch.outdoor_relay_1_switch
      - switch.indoor_relay_2_switch

- alias: 'Turn on Family room light when away'
  initial_state: 'on'
  hide_entity: False
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.android74dfa4b8d741c940
        state: 'not home'
      - condition: state
        entity_id: device_tracker.android832f34d810304a42
        state: 'not home'
  trigger:
      platform: time
      at: '16:33:00'
  action:
      service: switch.turn_on
      entity_id:
       - switch.indoor_relay_2_switch

- alias: 'Turn off Family room light when away'
  initial_state: 'on'
  hide_entity: False
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.android74dfa4b8d741c940
        state: 'not home'
      - condition: state
        entity_id: device_tracker.android832f34d810304a42
        state: 'not home'
  trigger:
      platform: time
      at: '22:07:00'
  action:
      service: switch.turn_off
      entity_id:
       - switch.indoor_relay_2_switch

- alias: 'Turn on Living room light when away'
  initial_state: 'on'
  hide_entity: False
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.android74dfa4b8d741c940
        state: 'not home'
      - condition: state
        entity_id: device_tracker.android832f34d810304a42
        state: 'not home'
  trigger:
      platform: time
      at: '17:11:00'
  action:
      service: switch.turn_on
      entity_id:
       - switch.front_room_plug_switch

- alias: 'Turn off Living room light when away'
  initial_state: 'on'
  hide_entity: False
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.android74dfa4b8d741c940
        state: 'not home'
      - condition: state
        entity_id: device_tracker.android832f34d810304a42
        state: 'not home'
  trigger:
      platform: time
      at: '20:56:00'
  action:
      service: switch.turn_off
      entity_id:
       - switch.front_room_plug_switch

- alias: 'Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: 'Failed to Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 24
  action:
    service: notify.klint_phone
    data:
      message: 'SSL Cert failed to auto renew.'
      data:
        icon: 'https://goo.gl/xeetdy'

- alias: 'Turn off straightener after 1 hour'
  trigger: 
    platform: state
    entity_id: switch.straightener_relay_switch
    from: 'off'
    to: 'on'
    for:
      hours: 1
  action: 
    service: switch.turn_off
    entity_id: switch.straightener_relay_switch

- alias: 'Garage Door Still Open'
  trigger:
    platform: state
    entity_id: cover.overhead_garage_door
    from: 'closed'
    to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: script.garage_door_alarm

- alias: 'Clear Garage Door Still Open' 
  trigger:
    platform: state
    entity_id: cover.overhead_garage_door
    to: 'closed'
  action:
    service: homeassistant.turn_off
    entity_id: script.garage_door_alarm

- alias: 'Water In Basement'
  trigger:
    platform: state
    entity_id: zwave.flood_sensor_water_main
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.basement_water_alarm

- alias: 'Clear Water In Basement'
  trigger:
    platform: state
    entity_id: zwave.flood_sensor_water_main
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: script.basement_water_alarm

# Alarm Stuff

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.window_front_left_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.window_front_right_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.window_basement_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: binary_sensor.window_front_left_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.window_front_right_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.window_basement_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_home'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- alias: 'Send notification when alarm is triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    service: notify.klint_phone
    data:
      message: 'ALARM! Home alarm has been triggered!'
      data:
        icon: 'https://goo.gl/xeetdy'

- alias: 'Send notification when 3D print complete'
  trigger:
    - platform: state
      entity_id: sensor.octoprint_current_state
      from: 'Printing'
      to: 'Operational'
  action:
    service: notify.klint_phone
    data:
      message: 'Print Complete!'
      data:
          icon: 'https://raw.githubusercontent.com/guysoft/OctoPi/devel/media/OctoPi.png'
